config/routes.rb
Rails.application.routes.draw do
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
  validates :name, :address, :picture_url, :price_per_night, :description, presence: true
  validates :name, :address, length: { minimum: 5 }
  validates :description, length: { minimum: 15 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: %i[destroy edit update show]
  def index
    @flats = Flat.all
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    if @flat.save
      redirect_to flats_path
    else
      render :new
    end
  end

  def update
    if @flat.update(flat_params)
      redirect_to flats_path
    else
      render :new
    end
  end

  def destroy
    @flat.destroy
    redirect_to flats_path
  end

  private

  def set_flat
    @flat = Flat.find(params[:id])
  end

  def flat_params
    params.require(:flat)
          .permit(:name, :address, :description, :price_per_night)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_form.html.erb
<%= simple_form_for(@flat) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :description %>
  <%= f.input :price_per_night %>
  <%= f.input :picture_url %>
  <%= f.submit class: "btn btn-primary float-right" %>
<% end %>

app/views/flats/_navbar.html.erb
<nav class="navbar d-flex justify-content-between bg-light">
  <div>
    <%= link_to 'Simple Airbnb', flats_path, class: "btn" %>
  </div>
  <div>
    <%= link_to 'Add flat', new_flat_path, class: "btn btn-outline-primary" %>
  </div>
</nav>

app/views/flats/edit.html.erb
<%= render 'navbar' %>
<div class="container mt-4">
  <h1 class="row justify-content-center py-4">Edit <%= @flat.name %></h1>
  <div class="row justify-content-center">
    <div class="col-6">
      <%= render 'form', flat: @flat %>
    </div>
  </div>
</div>

app/views/flats/index.html.erb
<%= render 'navbar' %>

<div class="container my-4">
  <h1 class="py-4">All our flats (<%= @flats.size %>)</h1>
    <div class="row">
      <% @flats.each do |flat| %>
        <div class="col-4">
          <div class="card shadow-sm rounded-0 mb-4">
            <img src="<%= flat.picture_url %>" class="card-img-top" alt="<%= flat.name %>">
            <div class="card-footer card-body border flex-grow-1 card-height-fix">
              <h5 class="card-title">
                <%= flat.name %>
              </h5>
              <p class="card-text">
                <%= flat.description %>
              </p>
              <div class="card-icons d-flex">
                <div>
                  <i class="fas fa-users"></i>
                  <%= flat.number_of_guests %>
                </div>
                <div>
                  <strong class="mr-1">€</strong><%= flat.price_per_night %>
                </div>
              </div>
            </div>
            <div class="card-body py-2 px-4 flex-grow-0">
              <%= link_to "More info", flat_path(flat), class: 'text-primary mr-1'  %>
              <%= link_to "Edit", edit_flat_path(flat), class: 'text-warning mr-1'  %>
              <%= link_to "Remove", flat_path(flat), method: 'delete', class: 'text-danger'  %>
            </div>
          </div>
        </div>
      <% end %>
  </div>
</div>

app/views/flats/new.html.erb
<%= render 'navbar' %>
<div class="container mt-4">
  <h1 class="row justify-content-center py-4">Add a new flat</h1>
  <div class="row justify-content-center">
    <div class="col-6">
      <%= render 'form', flat: @flat %>
    </div>
  </div>
</div>

app/views/flats/show.html.erb
<%= render 'navbar' %>
<div class="banner">
  <img src="<%= @flat.picture_url %>" alt="<%= @flat.name %>">
</div>
<div class="container">
  <div class="row mt-n4">
    <div class="col-8">

      <div class="card-group flex-column">
        <div class="card mt-n4 bg-light shadow-sm">
          <div class="card-body">
            <div class="card-title">
              <h2><%= @flat.name %></h2>
            </div>
            <div class="card-text font-weight-lighter">
              <p><%= @flat.address %></p>
            </div>
          </div>
        </div>

        <div class="card mt-2 bg-light shadow-sm border">
          <div class="card-body">
            <div class="card-title">
              <h4>A bit more about this flat...</h4>
            </div>
            <div class="card-text">
              <p><%= @flat.description %></p>
            </div>
          </div>
        </div>
      </div>

    </div>

      <div class="col-4">

        <div class="card-group flex-column">
          <div class="card mt-n4 bg-light shadow-sm">
            <div class="card-body">
              <div class="card-title">
                <h6>Book this place!</h6>
              </div>
            </div>
          </div>
        </div>

        <div class="card-group flex-column">
          <div class="card mt-2 bg-light shadow-sm">
            <div class="card-body">
              <div class="card-title">
                <h6>Book this place!</h6>
              </div>
            </div>
          </div>
        </div>

      </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>